import assert from"node:assert/strict";import{readdir,readFile}from"node:fs/promises";import test from"node:test";import{PGlite}from"@electric-sql/pglite";
const migrations=new URL("../supabase/migrations/",import.meta.url),seed=new URL("../supabase/seed.sql",import.meta.url),orgA="20000000-0000-4000-8000-000000000001",orgB="20000000-0000-4000-8000-000000000002",owner="10000000-0000-4000-8000-000000000001",manager="10000000-0000-4000-8000-000000000002",accountant="10000000-0000-4000-8000-000000000003",viewer="10000000-0000-4000-8000-000000000004",ownerB="10000000-0000-4000-8000-000000000005";
async function setup(){const d=new PGlite();await d.exec(`create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create role anon nologin;create role authenticated nologin;`);for(const f of(await readdir(migrations)).filter(x=>x.endsWith(".sql")).sort())await d.exec(await readFile(new URL(f,migrations),"utf8"));await d.exec(await readFile(seed,"utf8"));await d.query("insert into auth.users values($1,'b@test')",[ownerB]);await d.query("insert into organizations(id,name,created_by) values($1,'منشأة B',$2)",[orgB,ownerB]);await d.query("insert into organization_members(organization_id,user_id,role) values($1,$2,'owner')",[orgB,ownerB]);await d.query("insert into properties(organization_id,name,property_type,city,district) values($1,'عقار B','عمارة','الرياض','الملقا')",[orgB]);return d;}
async function as(d,id,role="authenticated"){await d.exec(`reset role;set role ${role}`);await d.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
test("RLS tenant and role matrix",{timeout:60000},async t=>{const d=await setup();try{
await t.test("A cannot read B",async()=>{await as(d,owner);const r=await d.query("select organization_id from properties");assert.ok(r.rows.every(x=>x.organization_id===orgA));});
await t.test("A cannot insert B",async()=>{await as(d,owner);await assert.rejects(()=>d.query("insert into properties(organization_id,name,property_type,city,district) values($1,'x','x','x','x')",[orgB]));});
await t.test("A cannot update B",async()=>{await as(d,owner);assert.equal((await d.query("update properties set name='x' where organization_id=$1",[orgB])).affectedRows,0);});
await t.test("A cannot delete B",async()=>{await as(d,owner);assert.equal((await d.query("delete from properties where organization_id=$1",[orgB])).affectedRows,0);});
await t.test("viewer read only",async()=>{await as(d,viewer);assert.equal((await d.query("select count(*)::int n from units")).rows[0].n,23);await assert.rejects(()=>d.query("insert into properties(organization_id,name,property_type,city,district) values($1,'x','x','x','x')",[orgA]));});
await t.test("accountant cannot delete property",async()=>{await as(d,accountant);assert.equal((await d.query("delete from properties where organization_id=$1",[orgA])).affectedRows,0);});
await t.test("accountant cannot edit members",async()=>{await as(d,accountant);assert.equal((await d.query("update organization_members set role='viewer' where organization_id=$1",[orgA])).affectedRows,0);});
await t.test("manager cannot grant owner",async()=>{await as(d,manager);await assert.rejects(()=>d.query("update organization_members set role='owner' where organization_id=$1 and user_id=$2",[orgA,viewer]));});
await t.test("manager cannot delete organization",async()=>{await as(d,manager);await assert.rejects(()=>d.query("select delete_organization($1)",[orgA]));});
await t.test("accountant can add own payment",async()=>{await as(d,accountant);const r=await d.query("insert into payments(organization_id,lease_id,amount_paid,payment_date,created_by) values($1,'60000000-0000-4000-8000-000000000001',100,'2026-07-15',$2) returning created_by",[orgA,accountant]);assert.equal(r.rows[0].created_by,accountant);});
await t.test("accountant cannot spoof creator",async()=>{await as(d,accountant);await assert.rejects(()=>d.query("insert into payments(organization_id,lease_id,amount_paid,payment_date,created_by) values($1,'60000000-0000-4000-8000-000000000001',100,'2026-07-15',$2)",[orgA,owner]));});
await t.test("anonymous denied",async()=>{await as(d,"","anon");await assert.rejects(()=>d.query("select id from properties"));});
}finally{await d.exec("reset role");await d.close();}});
