import assert from"node:assert/strict";import test from"node:test";import{calculateCashFlow as cash,calculateCollectionRate as collection,calculateExpenseEfficiency as expense,calculateLeaseExpiryRisk as expiry,calculateOccupancyRate as occupancy,calculateOperatingHealthScore as health,calculatePropertyRentGap as propertyGap,calculateRentGap as gap,classifyRentGap,selectBenchmark,type BenchmarkCandidate}from"../lib/scoring/engine.ts";
test("1 full collection",()=>assert.equal(collection(100,100).value,100));
test("2 partial collection",()=>assert.equal(collection(100,40).value,40));
test("3 no due",()=>assert.equal(collection(0,0).availability,"insufficient_data"));
test("4 overdue",()=>assert.equal(collection(200,150).value,75));
test("5 occupied days",()=>assert.equal(occupancy(90,100).value,90));
test("6 vacant",()=>assert.equal(occupancy(0,100).value,0));
test("7 inactive",()=>assert.equal(occupancy(0,0).availability,"insufficient_data"));
test("8 maintenance excluded",()=>assert.equal(occupancy(80,80).value,100));
test("9 positive cash",()=>assert.equal(cash([{month:"1",inflow:10,outflow:2},{month:"2",inflow:10,outflow:2},{month:"3",inflow:10,outflow:2}]).status,"green"));
test("10 negative cash",()=>assert.equal(cash([{month:"1",inflow:2,outflow:5},{month:"2",inflow:2,outflow:6},{month:"3",inflow:2,outflow:7}]).status,"red"));
test("11 volatile cash",()=>assert.equal(cash([{month:"1",inflow:20,outflow:1},{month:"2",inflow:1,outflow:12},{month:"3",inflow:9,outflow:6}]).status,"yellow"));
test("12 negative gap",()=>assert.equal(gap(45,50).percentage,-10));
test("13 positive gap",()=>assert.equal(gap(55,50).percentage,10));
test("14 zero gap",()=>assert.equal(gap(50,50).classification,"قريب من السوق"));
test("15 missing benchmark",()=>assert.equal(gap(50,null).percentage,null));
test("16 weighted property gap",()=>assert.equal(propertyGap([{occupied:true,currentAnnualRent:40,marketAnnualRent:50},{occupied:true,currentAnnualRent:120,marketAnnualRent:100}]).percentage,6.67));
test("17 income opportunity",()=>assert.equal(propertyGap([{occupied:true,currentAnnualRent:40,marketAnnualRent:50},{occupied:true,currentAnnualRent:120,marketAnnualRent:100}]).possibleAnnualIncrease,10));
test("18 expiry risk",()=>assert.equal(expiry(25,100).value,25));
test("19 health weights",()=>assert.equal(health({amountDue:100,amountCollected:90,occupiedUnitDays:80,availableUnitDays:100,paidExpenses:18,activeAnnualRent:100,expiringAnnualRent:20}).score,87.5));
test("20 snapshot inputs",()=>{const i={amountDue:100,amountCollected:100,occupiedUnitDays:100,availableUnitDays:100,paidExpenses:10,activeAnnualRent:100,expiringAnnualRent:0},r=health(i);assert.deepEqual(r.inputs,i);assert.equal(r.formulaVersion,"v1.0.0")});
test("21 missing component no reweight",()=>assert.equal(health({amountDue:0,amountCollected:0,occupiedUnitDays:1,availableUnitDays:1,paidExpenses:0,activeAnnualRent:1,expiringAnnualRent:0}).score,null));
test("22 expense bands",()=>assert.equal(expense(35,100).score,60));
test("23 three cash months required",()=>assert.equal(cash([{month:"1",inflow:1,outflow:0},{month:"2",inflow:1,outflow:0}]).status,"insufficient_data"));
test("24 far above label",()=>assert.equal(classifyRentGap(13),"أعلى كثيرًا من السوق"));
test("25 benchmark source and date",()=>{const base={city:"الرياض",district:"طويق",unitType:"شقة",bedrooms:2,areaMinSqm:70,areaMaxSqm:100,sampleCount:5} as const;const c:BenchmarkCandidate[]=[{...base,id:"old",annualMarketRent:48,sourceType:"executed_contract",periodEnd:"2026-03-31"},{...base,id:"new",annualMarketRent:50,sourceType:"executed_contract",periodEnd:"2026-06-30"},{...base,id:"listing",annualMarketRent:60,sourceType:"asking_listing",periodEnd:"2026-07-01"}];assert.equal(selectBenchmark(c,{city:"الرياض",district:"طويق",unitType:"شقة",bedrooms:2,areaSqm:85},"executed_contract")?.id,"new")});
