import assert from"node:assert/strict";import{readdir,readFile}from"node:fs/promises";import test from"node:test";import{PGlite}from"@electric-sql/pglite";
const migrations=new URL("../supabase/migrations/",import.meta.url),seed=new URL("../supabase/seed.sql",import.meta.url),org="20000000-0000-4000-8000-000000000001",property="30000000-0000-4000-8000-000000000001",owner="10000000-0000-4000-8000-000000000001",viewer="10000000-0000-4000-8000-000000000004";
async function setup(){const d=new PGlite();await d.exec(`create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create role anon nologin;create role authenticated nologin;`);for(const file of(await readdir(migrations)).filter(x=>x.endsWith(".sql")).sort())await d.exec(await readFile(new URL(file,migrations),"utf8"));await d.exec(await readFile(seed,"utf8"));return d;}
async function as(d,user){await d.exec("reset role;set role authenticated");await d.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);}
test("stage five workflows are atomic and role protected",{timeout:60_000},async()=>{const d=await setup();try{
  await as(d,viewer);await assert.rejects(()=>d.query(`select create_unit_with_history($1,$2,'Z99','شقة',2::smallint,2::numeric,90::numeric,1::smallint,'vacant',48000::numeric,'','2026-07-15')`,[org,property]));
  await as(d,owner);const created=await d.query(`select create_unit_with_history($1,$2,'Z99','شقة',2::smallint,2::numeric,90::numeric,1::smallint,'vacant',48000::numeric,'','2026-07-15') id`,[org,property]);const unit=created.rows[0].id;
  const history=await d.query("select status,start_date::text from unit_status_periods where unit_id=$1",[unit]);assert.deepEqual(history.rows,[{status:"vacant",start_date:"2026-07-15"}]);
  const tenant=await d.query("insert into tenants(organization_id,full_name) values($1,'مستأجر اختبار المرحلة الخامسة') returning id",[org]);
  const schedule=JSON.stringify([{due_date:"2026-07-15",amount_due:4000},{due_date:"2026-08-15",amount_due:4000}]);
  const createdLease=await d.query(`select create_lease_with_schedule($1,$2,$3,$4,'TEST-5','2026-07-15','2027-07-14',48000,'monthly',1000,5,'active',$5::jsonb,'2026-07-15') id`,[org,property,unit,tenant.rows[0].id,schedule]);const lease=createdLease.rows[0].id;
  assert.equal((await d.query("select count(*)::int n from lease_payment_schedules where lease_id=$1",[lease])).rows[0].n,2);assert.equal((await d.query("select status from units where id=$1",[unit])).rows[0].status,"occupied");
  await d.query("select terminate_lease($1,$2,'2026-07-15')",[org,lease]);assert.equal((await d.query("select status from leases where id=$1",[lease])).rows[0].status,"terminated");assert.equal((await d.query("select status from units where id=$1",[unit])).rows[0].status,"vacant");assert.equal((await d.query("select status from lease_payment_schedules where lease_id=$1 and due_date='2026-08-15'",[lease])).rows[0].status,"cancelled");
}finally{await d.exec("reset role");await d.close();}});
