"use server";

import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {sanitizeInternalPath} from "@/lib/auth/navigation.ts";
import {requireCapability} from "@/lib/auth/session.ts";
import {getRiyadhToday} from "@/lib/domain/business-date.ts";
import {isUuid,isValidIsoDate} from "@/lib/domain/validation.ts";
import {createCurrentPropertySnapshot} from "@/lib/data/operations.ts";
import {createClient} from "@/lib/supabase/server.ts";

const expenseStatuses=["pending","paid","cancelled"] as const;
const expenseTypes=["electricity","water","cleaning","maintenance","management","insurance","government_fees","other"] as const;
const marketSourceTypes=["executed_contract","asking_listing","manual_estimate"] as const;

function text(data:FormData,name:string,max=500){const value=data.get(name);return typeof value==="string"?value.trim().slice(0,max):"";}
function optionalText(data:FormData,name:string,max=500){return text(data,name,max)||null;}
function identifier(data:FormData,name:string){const value=text(data,name,40);if(!isUuid(value))throw new Error("المعرّف غير صحيح.");return value;}
function optionalIdentifier(data:FormData,name:string){const value=text(data,name,40);if(!value)return null;if(!isUuid(value))throw new Error("المعرّف غير صحيح.");return value;}
function numeric(data:FormData,name:string,{min=0,max=99_999_999,optional=false}:{min?:number;max?:number;optional?:boolean}={}){const raw=text(data,name,50);if(optional&&!raw)return null;const value=Number(raw);if(!Number.isFinite(value)||value<min||value>max)throw new Error("قيمة رقمية غير صحيحة.");return value;}
function integer(data:FormData,name:string,{min=0,max=100_000,optional=false}:{min?:number;max?:number;optional?:boolean}={}){const value=numeric(data,name,{min,max,optional});if(value===null)return null;if(!Number.isInteger(value))throw new Error("اكتب رقمًا صحيحًا.");return value;}
function safeReturn(data:FormData,fallback:string){const value=sanitizeInternalPath(data.get("returnTo"),fallback),pathname=new URL(value,"https://aqarpro.invalid").pathname,segments=pathname.split("/").filter(Boolean),propertyPath=segments.length===2&&segments[0]==="properties"&&isUuid(segments[1]??"");return ["/payments","/expenses","/market-benchmarks","/score-history"].includes(pathname)||propertyPath?value:fallback;}
function notice(path:string,message:string,tone:"success"|"error"="success"):never{const separator=path.includes("?")?"&":"?";redirect(`${path}${separator}${tone}=${encodeURIComponent(message)}`);}
function refreshOperations(propertyId?:string){revalidatePath("/dashboard");revalidatePath("/payments");revalidatePath("/expenses");revalidatePath("/market-benchmarks");revalidatePath("/score-history");revalidatePath("/properties");if(propertyId)revalidatePath(`/properties/${propertyId}`);}
function friendly(error:{code?:string}|null,fallback:string){if(error?.code==="22003")return"المبلغ يتجاوز المتبقي على الاستحقاق.";if(error?.code==="23505")return"يوجد سجل آخر بالقيمة نفسها.";if(error?.code==="23503")return"الربط بين العقار والوحدة غير صحيح.";if(error?.code==="42501")return"ليس لديك الصلاحية اللازمة.";return fallback;}

export async function recordPaymentAction(data:FormData){
  const context=await requireCapability("finance:write"),path=safeReturn(data,"/payments");let scheduleId:string,paymentDate:string,method:string,reference:string|null,notes:string|null,mode:string,requested:number;
  try{scheduleId=identifier(data,"scheduleId");paymentDate=text(data,"paymentDate",10);method=text(data,"paymentMethod",60);reference=optionalText(data,"referenceNumber",100);notes=optionalText(data,"notes",500);mode=text(data,"paymentMode",20);requested=numeric(data,"amount",{min:.01})!;if(!isValidIsoDate(paymentDate)||paymentDate>getRiyadhToday())throw new Error("تاريخ الدفعة غير صحيح أو بعد اليوم.");if(mode!=="full"&&mode!=="partial")throw new Error("نوع التحصيل غير صحيح.");}catch(error){notice(path,error instanceof Error?error.message:"راجع بيانات الدفعة.","error");}
  const supabase=await createClient();let amount=requested;
  if(mode==="full"){const[{data:schedule,error:scheduleError},{data:payments,error:paymentsError}]=await Promise.all([supabase.from("lease_payment_schedules").select("id, amount_due").eq("organization_id",context.activeMembership.organizationId).eq("id",scheduleId).maybeSingle(),supabase.from("payments").select("amount_paid").eq("organization_id",context.activeMembership.organizationId).eq("payment_schedule_id",scheduleId).is("deleted_at",null)]);if(scheduleError||paymentsError||!schedule)notice(path,"تعذر قراءة المتبقي على الاستحقاق.","error");amount=Math.max(0,Number(schedule.amount_due)-(payments??[]).reduce((sum,item)=>sum+Number(item.amount_paid),0));if(amount<=0)notice(path,"هذا الاستحقاق مسدد بالكامل.","error");}
  const{error}=await supabase.rpc("record_schedule_payment",{p_organization_id:context.activeMembership.organizationId,p_schedule_id:scheduleId,p_amount:amount,p_payment_date:paymentDate,p_payment_method:method,p_reference_number:reference??"",p_notes:notes??""});if(error)notice(path,friendly(error,"تعذر تسجيل الدفعة."),"error");refreshOperations();notice(path,mode==="full"?"تم تسجيل التحصيل الكامل.":"تم تسجيل الدفعة الجزئية وتحديث حالة الاستحقاق.");
}

export async function updatePaymentAction(data:FormData){
  const context=await requireCapability("finance:write"),path=safeReturn(data,"/payments");let paymentId:string,amount:number,paymentDate:string;
  try{paymentId=identifier(data,"paymentId");amount=numeric(data,"amount",{min:.01})!;paymentDate=text(data,"paymentDate",10);if(!isValidIsoDate(paymentDate)||paymentDate>getRiyadhToday())throw new Error("تاريخ الدفعة غير صحيح أو بعد اليوم.");}catch(error){notice(path,error instanceof Error?error.message:"راجع بيانات الدفعة.","error");}
  const supabase=await createClient(),{error}=await supabase.from("payments").update({amount_paid:amount,payment_date:paymentDate,payment_method:optionalText(data,"paymentMethod",60),reference_number:optionalText(data,"referenceNumber",100),notes:optionalText(data,"notes",500)}).eq("organization_id",context.activeMembership.organizationId).eq("id",paymentId).is("deleted_at",null);if(error)notice(path,friendly(error,"تعذر تعديل الدفعة."),"error");refreshOperations();notice(path,"تم تعديل الدفعة وإعادة حساب الاستحقاق.");
}

export async function voidPaymentAction(data:FormData){const context=await requireCapability("finance:delete"),path=safeReturn(data,"/payments"),paymentId=identifier(data,"paymentId"),supabase=await createClient(),{error}=await supabase.rpc("void_payment",{p_organization_id:context.activeMembership.organizationId,p_payment_id:paymentId});if(error)notice(path,friendly(error,"تعذر إلغاء الدفعة."),"error");refreshOperations();notice(path,"تم إلغاء الدفعة منطقيًا وإعادة حساب المتبقي.");}

function expensePayload(data:FormData){const propertyId=identifier(data,"propertyId"),unitId=optionalIdentifier(data,"unitId"),categoryId=identifier(data,"categoryId"),amount=numeric(data,"amount",{min:.01})!,expenseDate=text(data,"expenseDate",10),status=text(data,"paymentStatus",20);if(!expenseStatuses.includes(status as (typeof expenseStatuses)[number]))throw new Error("حالة المصروف غير صحيحة.");if(!isValidIsoDate(expenseDate)||(status==="paid"&&expenseDate>getRiyadhToday()))throw new Error("تاريخ المصروف غير صحيح، ولا يمكن تسجيل مصروف مدفوع بتاريخ مستقبلي.");const description=text(data,"description",500);if(!description)throw new Error("وصف المصروف مطلوب.");return{propertyId,unitId,categoryId,amount,expenseDate,status:status as (typeof expenseStatuses)[number],description,vendorName:optionalText(data,"vendorName",160)};}

export async function createExpenseAction(data:FormData){const context=await requireCapability("finance:write"),path=safeReturn(data,"/expenses");let value:ReturnType<typeof expensePayload>;try{value=expensePayload(data);}catch(error){notice(path,error instanceof Error?error.message:"راجع بيانات المصروف.","error");}const supabase=await createClient(),{error}=await supabase.from("expenses").insert({organization_id:context.activeMembership.organizationId,property_id:value.propertyId,unit_id:value.unitId,expense_category_id:value.categoryId,amount:value.amount,expense_date:value.expenseDate,payment_status:value.status,description:value.description,vendor_name:value.vendorName,created_by:context.user.id});if(error)notice(path,friendly(error,"تعذر إضافة المصروف."),"error");refreshOperations(value.propertyId);notice(path,"تمت إضافة المصروف وتحديث التدفق النقدي.");}

export async function updateExpenseAction(data:FormData){const context=await requireCapability("finance:write"),path=safeReturn(data,"/expenses");let expenseId:string,value:ReturnType<typeof expensePayload>;try{expenseId=identifier(data,"expenseId");value=expensePayload(data);}catch(error){notice(path,error instanceof Error?error.message:"راجع بيانات المصروف.","error");}const supabase=await createClient(),{error}=await supabase.from("expenses").update({property_id:value.propertyId,unit_id:value.unitId,expense_category_id:value.categoryId,amount:value.amount,expense_date:value.expenseDate,payment_status:value.status,description:value.description,vendor_name:value.vendorName}).eq("organization_id",context.activeMembership.organizationId).eq("id",expenseId).is("deleted_at",null);if(error)notice(path,friendly(error,"تعذر تعديل المصروف."),"error");refreshOperations(value.propertyId);notice(path,"تم حفظ تعديلات المصروف.");}

export async function deleteExpenseAction(data:FormData){const context=await requireCapability("finance:delete"),path=safeReturn(data,"/expenses"),expenseId=identifier(data,"expenseId"),supabase=await createClient(),{error}=await supabase.from("expenses").update({deleted_at:new Date().toISOString()}).eq("organization_id",context.activeMembership.organizationId).eq("id",expenseId).is("deleted_at",null);if(error)notice(path,"تعذر حذف المصروف.","error");refreshOperations();notice(path,"تم حذف المصروف منطقيًا.");}

export async function createExpenseCategoryAction(data:FormData){const context=await requireCapability("properties:write"),path=safeReturn(data,"/expenses"),name=text(data,"categoryName",100),type=text(data,"categoryType",30);if(name.length<2||!expenseTypes.includes(type as (typeof expenseTypes)[number]))notice(path,"راجع اسم التصنيف ونوعه.","error");const supabase=await createClient(),{error}=await supabase.from("expense_categories").insert({organization_id:context.activeMembership.organizationId,name,category_type:type});if(error)notice(path,friendly(error,"تعذر إضافة التصنيف."),"error");refreshOperations();notice(path,"تمت إضافة تصنيف المصروف.");}

function benchmarkPayload(data:FormData){const city=text(data,"city",60),district=text(data,"district",60),unitType=text(data,"unitType",60),sourceName=text(data,"sourceName",120),sourceType=text(data,"sourceType",30),periodStart=text(data,"periodStart",10),periodEnd=text(data,"periodEnd",10),annualMarketRent=numeric(data,"annualMarketRent",{min:.01})!,lower=numeric(data,"lowerRentRange",{optional:true}),upper=numeric(data,"upperRentRange",{optional:true}),areaMin=numeric(data,"areaMinSqm",{min:.01,optional:true}),areaMax=numeric(data,"areaMaxSqm",{min:.01,optional:true});if(!city||!district||!unitType||!sourceName||!marketSourceTypes.includes(sourceType as (typeof marketSourceTypes)[number]))throw new Error("أكمل بيانات الموقع والوحدة والمصدر.");if(!isValidIsoDate(periodStart)||!isValidIsoDate(periodEnd)||periodStart>periodEnd||periodEnd>getRiyadhToday())throw new Error("فترة بيانات السوق غير صحيحة أو تقع في المستقبل.");if(areaMin!==null&&areaMax!==null&&areaMin>areaMax)throw new Error("بداية نطاق المساحة يجب ألا تتجاوز نهايته.");if((lower!==null&&lower>annualMarketRent)||(upper!==null&&upper<annualMarketRent))throw new Error("نطاق الإيجار يجب أن يحتوي قيمة السوق.");return{city,district,unitType,bedrooms:integer(data,"bedrooms",{max:30,optional:true}),areaMin,areaMax,annualMarketRent,lower,upper,sampleCount:integer(data,"sampleCount",{min:1,optional:true}),sourceName,sourceType:sourceType as (typeof marketSourceTypes)[number],periodStart,periodEnd,notes:optionalText(data,"notes",700)};}

export async function createBenchmarkAction(data:FormData){const context=await requireCapability("benchmarks:write"),path=safeReturn(data,"/market-benchmarks");let value:ReturnType<typeof benchmarkPayload>;try{value=benchmarkPayload(data);}catch(error){notice(path,error instanceof Error?error.message:"راجع بيانات السوق.","error");}const supabase=await createClient(),{error}=await supabase.from("market_benchmarks").insert({organization_id:context.activeMembership.organizationId,city:value.city,district:value.district,unit_type:value.unitType,bedrooms:value.bedrooms,area_min_sqm:value.areaMin,area_max_sqm:value.areaMax,annual_market_rent:value.annualMarketRent,lower_rent_range:value.lower,upper_rent_range:value.upper,sample_count:value.sampleCount,source_name:value.sourceName,source_type:value.sourceType,period_start:value.periodStart,period_end:value.periodEnd,entered_manually:true,notes:value.notes,created_by:context.user.id});if(error)notice(path,friendly(error,"تعذر إضافة مرجع السوق."),"error");refreshOperations();notice(path,"تم حفظ مرجع السوق وإعادة ربط المقارنات.");}

export async function updateBenchmarkAction(data:FormData){const context=await requireCapability("benchmarks:write"),path=safeReturn(data,"/market-benchmarks");let benchmarkId:string,value:ReturnType<typeof benchmarkPayload>;try{benchmarkId=identifier(data,"benchmarkId");value=benchmarkPayload(data);}catch(error){notice(path,error instanceof Error?error.message:"راجع بيانات السوق.","error");}const supabase=await createClient(),{error}=await supabase.from("market_benchmarks").update({city:value.city,district:value.district,unit_type:value.unitType,bedrooms:value.bedrooms,area_min_sqm:value.areaMin,area_max_sqm:value.areaMax,annual_market_rent:value.annualMarketRent,lower_rent_range:value.lower,upper_rent_range:value.upper,sample_count:value.sampleCount,source_name:value.sourceName,source_type:value.sourceType,period_start:value.periodStart,period_end:value.periodEnd,notes:value.notes}).eq("organization_id",context.activeMembership.organizationId).eq("id",benchmarkId);if(error)notice(path,friendly(error,"تعذر تعديل مرجع السوق."),"error");refreshOperations();notice(path,"تم تحديث مرجع السوق.");}

export async function deleteBenchmarkAction(data:FormData){const context=await requireCapability("benchmarks:delete"),path=safeReturn(data,"/market-benchmarks"),benchmarkId=identifier(data,"benchmarkId"),supabase=await createClient(),{error}=await supabase.from("market_benchmarks").delete().eq("organization_id",context.activeMembership.organizationId).eq("id",benchmarkId);if(error)notice(path,"تعذر حذف مرجع السوق.","error");refreshOperations();notice(path,"تم حذف مرجع السوق.");}

export async function createSnapshotAction(data:FormData){const context=await requireCapability("snapshots:create"),path=safeReturn(data,"/score-history"),propertyId=identifier(data,"propertyId");try{await createCurrentPropertySnapshot(context.activeMembership.organizationId,propertyId);}catch(error){notice(path,error instanceof Error?error.message:"تعذر إنشاء لقطة المؤشر.","error");}refreshOperations(propertyId);notice(path,"تم حساب لقطة اليوم وحفظ مدخلاتها ونتائجها.");}
